#!/usr/bin/env python3
"""Compare the frozen analytic profile A with a separately minimized profile B.

This is a read-only audit helper.  It deliberately does not claim that profile
B is a valid zero-mode continuation; the executable's provenance guard is
audited separately.  The output is a compact JSON summary so large VTK files
need not be copied off the workstation.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def read_vtk(path: Path) -> tuple[np.ndarray, tuple[int, int, int]]:
    with path.open("r", encoding="ascii") as f:
        header = [next(f) for _ in range(10)]
    dims = tuple(int(x) for x in header[4].split()[1:4])
    if header[2].strip() != "ASCII" or not header[8].startswith("SCALARS "):
        raise ValueError(f"unsupported VTK header in {path}")
    data = np.loadtxt(path, skiprows=10, dtype=np.float64)
    n = int(np.prod(dims))
    if data.size != n:
        raise ValueError(f"{path}: expected {n} scalars, got {data.size}")
    return data, dims


def h(phi: np.ndarray) -> np.ndarray:
    return phi**3 * (6.0 * phi**2 - 15.0 * phi + 10.0)


def radial_profile(field: np.ndarray, dims: tuple[int, int, int], center: tuple[float, float, float]) -> list[dict[str, float]]:
    a = field.reshape(dims)
    ix, iy, iz = np.indices(dims, dtype=np.float64)
    d2 = np.zeros(dims, dtype=np.float64)
    for q, c, n in ((ix, center[0], dims[0]), (iy, center[1], dims[1]), (iz, center[2], dims[2])):
        d = np.abs(q - c)
        d = np.minimum(d, n - d)
        d2 += d * d
    r = np.sqrt(d2)
    bins = np.arange(0.0, 26.0, 1.0)
    out = []
    for lo, hi in zip(bins[:-1], bins[1:]):
        mask = (r >= lo) & (r < hi)
        if np.any(mask):
            out.append({"r_nm": float((lo + hi) / 2.0), "mean": float(np.mean(a[mask])), "count": int(np.count_nonzero(mask))})
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--phi-a", type=Path, required=True)
    ap.add_argument("--xb-a", type=Path, required=True)
    ap.add_argument("--phi-b", type=Path, required=True)
    ap.add_argument("--xb-b", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    phi_a, dims = read_vtk(args.phi_a)
    phi_b, dims_b = read_vtk(args.phi_b)
    xb_a, dims_xa = read_vtk(args.xb_a)
    xb_b, dims_xb = read_vtk(args.xb_b)
    if not (dims == dims_b == dims_xa == dims_xb):
        raise ValueError("profile grids do not match")

    dphi = np.abs(phi_b - phi_a)
    dxb = np.abs(xb_b - xb_a)
    ha = h(phi_a)
    hb = h(phi_b)
    # The artifact fraction is deliberately a geometric diagnostic, not a
    # physical acceptance criterion for the blocked profile-B handoff.
    artifact = dphi > 1.0e-2
    result = {
        "grid": list(dims),
        "center_nm": [dims[0] / 2.0, dims[1] / 2.0, dims[2] / 2.0],
        "profile_a": {
            "mean_phi": float(np.mean(phi_a)),
            "mean_h_phi": float(np.mean(ha)),
            "mean_xB": float(np.mean(xb_a)),
            "phi_min": float(np.min(phi_a)),
            "phi_max": float(np.max(phi_a)),
            "xB_min": float(np.min(xb_a)),
            "xB_max": float(np.max(xb_a)),
        },
        "profile_b_minimize_only": {
            "mean_phi": float(np.mean(phi_b)),
            "mean_h_phi": float(np.mean(hb)),
            "mean_xB": float(np.mean(xb_b)),
            "phi_min": float(np.min(phi_b)),
            "phi_max": float(np.max(phi_b)),
            "xB_min": float(np.min(xb_b)),
            "xB_max": float(np.max(xb_b)),
        },
        "difference": {
            "mean_abs_phi": float(np.mean(dphi)),
            "max_abs_phi": float(np.max(dphi)),
            "mean_abs_xB": float(np.mean(dxb)),
            "max_abs_xB": float(np.max(dxb)),
            "artifact_fraction_abs_phi_gt_1e-2": float(np.mean(artifact)),
            "relative_mean_h_change": float((np.mean(hb) - np.mean(ha)) / np.mean(ha)),
        },
        "profile_b_runtime_status": "NOT_A_ZERO_MODE_HANDOFF",
        "profile_b_note": "Generated by full-model minimize; clean branch PF_CONSERVED_Y_ZERO_MODE_V1 rejects minimize/raw/VTK continuation.",
        "radial_profile_phi_a": radial_profile(phi_a, dims, (dims[0] / 2.0, dims[1] / 2.0, dims[2] / 2.0)),
        "radial_profile_phi_b": radial_profile(phi_b, dims, (dims[0] / 2.0, dims[1] / 2.0, dims[2] / 2.0)),
        "radial_profile_xB_a": radial_profile(xb_a, dims, (dims[0] / 2.0, dims[1] / 2.0, dims[2] / 2.0)),
        "radial_profile_xB_b": radial_profile(xb_b, dims, (dims[0] / 2.0, dims[1] / 2.0, dims[2] / 2.0)),
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result["difference"], sort_keys=True))


if __name__ == "__main__":
    main()
