#!/usr/bin/env python3
"""Prepare provenance-locked coarse4 fixed-Ctot smoke inputs."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import math
from pathlib import Path
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import Unit_Psedobinary as unit  # noqa: E402


MODEL_NAME = "fixed_ctot_gp_coarse4_multifidelity_v1"
MODEL_VERSION = "1"
UNCERTAINTY_VERSION = "precalibration_hard_gate_v0"
COARSE_LAMBDA_NM = 4.0
COARSE_DX_NM = 1.0
MECHANICS_PRECISION_MODE = "FP32_SPECTRAL"
MECHANICS_ACCEPTANCE_MODE = "FP32_NORMALIZED_BACKWARD_ERROR_V1"
MECHANICS_ETA_FLOOR_VERSION = "COARSE4_FP32_ETA_FLOOR_16_32_V1"
MECHANICS_ETA_FLOOR = 6.42480737461158500e-08
MECHANICS_SAFETY_FACTOR = 4.0
MECHANICS_ETA_ACCEPT = MECHANICS_SAFETY_FACTOR * MECHANICS_ETA_FLOOR
MECHANICS_DOUBLE_ORACLE_CONTRACT_HASH = (
    "cc4cad8955684d45d34ca9db7d1b300dd82acc1fc7473ff52b23cd0f5cd3ae3e"
)
MECHANICS_RESIDUAL_NORMALIZATION_VERSION = (
    "DEALIASED_REAL_DIVSIGMA_OVER_KMAX_STRESS_V1"
)
CALIBRATION_PROTOCOL = {
    "schema": "coarse4_calibration_protocol_v1",
    "fit_cases": [
        "T400_planar_small_driving_growth",
        "T400_planar_small_driving_dissolution",
    ],
    "weights": {"matrix_flux": 0.4, "beta_inventory": 0.4, "trajectory": 0.2},
    "constraints": {"a_M_min": 0.0, "free_parameter_count": 1},
    "heldout_refit_allowed": False,
}


def sha256_files(paths: list[Path]) -> str:
    digest = hashlib.sha256()
    for path in sorted(paths, key=lambda item: str(item)):
        digest.update(str(path.relative_to(ROOT)).encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def canonical_hash(payload: object) -> str:
    encoded = json.dumps(
        payload, sort_keys=True, separators=(",", ":"), allow_nan=False
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def portable_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return path.name


def h_switch(phi: np.ndarray) -> np.ndarray:
    return phi**3 * (6.0 * phi**2 - 15.0 * phi + 10.0)


def write_params(path: Path, values: dict[str, object]) -> None:
    lines = [
        "# Generated by scripts/prepare_coarse4_multifidelity.py",
        "# coarse4 is a calibrated surrogate; lambda=4 nm is not a physical interface claim.",
    ]
    for key in sorted(values):
        value = values[key]
        if isinstance(value, str):
            lines.append(f"{key}={value}")
        elif isinstance(value, int):
            lines.append(f"{key}={value}")
        else:
            lines.append(f"{key}={float(value):.17e}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def physical_payload() -> tuple[unit.PhysicalInputs, dict[str, object]]:
    inputs = copy.deepcopy(unit.load_physical_inputs(str(ROOT / "physical_inputs.example.json")))
    inputs.gamma = 0.168
    inputs.lambda_sm = COARSE_LAMBDA_NM * 1.0e-9
    inputs.dx = COARSE_DX_NM * 1.0e-9
    inputs.pf_dx = COARSE_DX_NM * 1.0e-9
    inputs.phys_dx_ref = COARSE_DX_NM * 1.0e-9
    inputs.temperature_C = 400.0
    inputs.dt = 1.0e-6
    inputs.L_phi_calibration_mode = "one_sided_diffusion_controlled"
    inputs.vf_init = 0.0
    inputs.vf_target = 0.04
    return inputs, unit.generate_payload(inputs)


def build_initial_state(
    output: Path, grid: int, x_matrix: float, fine_hash: str,
    calibration_hash: str,
) -> dict[str, object]:
    coordinates = (np.arange(grid, dtype=np.float64) + 0.5) * COARSE_DX_NM
    center = 0.5 * grid * COARSE_DX_NM
    radius = 0.25 * grid * COARSE_DX_NM
    half_width = 0.5 * COARSE_LAMBDA_NM
    line = 0.5 * (
        np.tanh((coordinates - (center - radius)) / half_width)
        - np.tanh((coordinates - (center + radius)) / half_width)
    )
    shape = (grid, grid, grid)
    phi = np.broadcast_to(line[:, None, None], shape).copy()
    x_b = np.full(shape, x_matrix, dtype=np.float64)
    h = h_switch(phi)
    ctot = h + (1.0 - h) * x_b
    phi.tofile(output / "phi_init.raw")
    x_b.tofile(output / "xB_init.raw")
    ctot.tofile(output / "Ctot_init.raw")
    metadata = {
        "schema": "coarse4_initial_state_v1",
        "Nx": grid,
        "Ny": grid,
        "Nz": grid,
        "dx_nm": COARSE_DX_NM,
        "interface_width_nm": COARSE_LAMBDA_NM,
        "dtype": "float64",
        "order": "C",
        "authoritative_state": "Ctot",
        "initial_geometry": "periodic_planar_slab",
        "initial_half_width_nm": radius,
        "mean_xBtot": float(ctot.mean()),
        "xB_max_safe": float(x_b.max()),
        "coarse_model_name": MODEL_NAME,
        "coarse_model_version": MODEL_VERSION,
        "fine_reference_hash": fine_hash,
        "coarse_calibration_hash": calibration_hash,
        "coarse_uncertainty_version": UNCERTAINTY_VERSION,
        "mechanics_precision_mode": MECHANICS_PRECISION_MODE,
        "mechanics_acceptance_mode": MECHANICS_ACCEPTANCE_MODE,
        "eta_floor_version": MECHANICS_ETA_FLOOR_VERSION,
        "eta_accept": MECHANICS_ETA_ACCEPT,
        "double_oracle_contract_hash": MECHANICS_DOUBLE_ORACLE_CONTRACT_HASH,
        "residual_normalization_version": MECHANICS_RESIDUAL_NORMALIZATION_VERSION,
    }
    (output / "init_meta.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
    )
    return metadata


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output-root", type=Path,
        default=ROOT / "tmp" / "coarse4_stage1_smoke",
    )
    parser.add_argument("--grid", type=int, default=16)
    args = parser.parse_args()
    if args.grid < 16 or args.grid % 2:
        raise ValueError("coarse4 smoke grid must be even and at least 16")

    reference_assets = [
        ROOT / "examples" / "correction2_selected_matrix_to_beta_mode.json",
        ROOT / "reports" / "pf_ctot_production_candidate" /
        "correction2_physical_lambda_metrics.csv",
        ROOT / "reports" / "pf_ctot_production_candidate" /
        "correction2_diffusion_limit_decision.md",
    ]
    for asset in reference_assets:
        if not asset.is_file():
            raise FileNotFoundError(asset)
    fine_hash = sha256_files(reference_assets)
    calibration_hash = canonical_hash(CALIBRATION_PROTOCOL)
    inputs, payload = physical_payload()
    overrides = dict(payload["main_cuda_overrides"])
    pf = payload["pf_params"]
    if not math.isclose(float(pf["W"]), 1.0, rel_tol=0.0, abs_tol=1.0e-14):
        raise RuntimeError("coarse W mapping is not one")
    if not math.isclose(float(pf["kappa_phi"]), 2.0, rel_tol=0.0, abs_tol=1.0e-13):
        raise RuntimeError("coarse kappa mapping is not two")
    if not math.isclose(float(pf["ic_phi_iface_w"]), 2.0, rel_tol=0.0, abs_tol=1.0e-14):
        raise RuntimeError("coarse interface is not four PF cells")

    out = args.output_root.resolve()
    out.mkdir(parents=True, exist_ok=True)
    state_meta = build_initial_state(
        out, args.grid, float(pf["ic_xB_eq_matrix"]), fine_hash,
        calibration_hash,
    )
    common: dict[str, object] = {
        **overrides,
        "pf_params_schema_version": 2,
        "model_mode": "two_phase",
        "PF_RESEARCH_MODEL": MODEL_NAME,
        "coarse_model_name": MODEL_NAME,
        "coarse_model_version": MODEL_VERSION,
        "fine_reference_hash": fine_hash,
        "coarse_calibration_hash": calibration_hash,
        "coarse_uncertainty_version": UNCERTAINTY_VERSION,
        "mechanics_precision_mode": MECHANICS_PRECISION_MODE,
        "mechanics_acceptance_mode": MECHANICS_ACCEPTANCE_MODE,
        "eta_floor_version": MECHANICS_ETA_FLOOR_VERSION,
        "eta_accept": MECHANICS_ETA_ACCEPT,
        "double_oracle_contract_hash": MECHANICS_DOUBLE_ORACLE_CONTRACT_HASH,
        "residual_normalization_version": MECHANICS_RESIDUAL_NORMALIZATION_VERSION,
        "GP_population_mode": "OFF",
        "composition_evolution_mode": "ctot_mimetic_be",
        "pf_composition_mode": "legacy",
        "pf_y_update_mode": "lagged_rhs",
        "ctot_phase_semismooth_pdas_enabled": 1,
        "ctot_phase_restart_solver_migration_allowed": 0,
        "ctot_nonlinear_max_iter": 200,
        "ctot_phase_linear_max_iter": 400,
        "ctot_phase_linear_rel_tol": 1.0e-10,
        "ctot_residual_abs_tol": 1.0e-10,
        "ctot_residual_rel_tol": 1.0e-8,
        "ctot_outer_max_iter": 20,
        "ctot_step_max_retries": 4,
        "ctot_retry_shrink_factor": 0.5,
        "ctot_dt_min_ratio": 1.0 / 64.0,
        "ctot_automatic_dt_growth": 0,
        "ctot_finite_interface_antitrapping_enabled": 0,
        "finite_interface_resolution_test_override": 0,
        "thermo_convex_extrapolation_enabled": 1,
        "coarse_interface_mobility_mode": "off",
        "coarse_interface_mobility_a_M": 0.0,
        "D_beta_for_calibration": 0.0,
        "y_update_mass_projection_enabled": 0,
        "diagnostic_rsmd_enabled": 0,
        "gp_nuc_enabled": 0,
        "enable_gp_assisted_beta_nucleation": 0,
        "gp_literature_model_enabled": 0,
        "gp_initial_population_enabled": 0,
        "gp_stochastic_enabled": 0,
        "gp_to_beta_enabled": 0,
        "enable_runtime_nucleus_library": 0,
        "beta_staged_conversion_enabled": 0,
        "gp_growth_enabled": 0,
        "gp_radius_evolution_enabled": 0,
        "gp_inventory_growth_enabled": 0,
        "enable_legacy_gp_storage_coupling": 0,
        "ctot_diagnostics_enabled": 1,
    }
    finite_lphi_diff = float(pf["L_phi"])
    cases: list[dict[str, object]] = []
    for phase_id, phase_mode in (
        ("finite_lphi_r0p90", "FINITE_LPHI_BE"),
        ("quasi_equilibrium", "QUASI_EQUILIBRIUM_FAST_INTERFACE_V1"),
    ):
        for elastic in (0, 1):
            case_id = f"{phase_id}_elastic{elastic}"
            values = dict(common)
            values["PHASE_KINETICS_MODE"] = phase_mode
            values["L_phi"] = 0.90 * finite_lphi_diff
            values["L_phi_code_value"] = 0.90 * finite_lphi_diff
            values["L_phi_physical_value"] = (
                0.90 * float(pf["L_phi_phys"])
            )
            values["elastic_enabled"] = elastic
            values["ctot_elastic_validation_enabled"] = elastic
            values["elastic_iter_max"] = 40 if elastic else 20
            values["init_case_tag"] = case_id
            param_path = out / f"{case_id}.params"
            write_params(param_path, values)
            cases.append({
                "case_id": case_id,
                "phase_mode": phase_mode,
                "elastic_enabled": bool(elastic),
                "elastic_iter_max": int(values["elastic_iter_max"]),
                "initial_state": "planar_slab",
                "init_phi_raw": "phi_init.raw",
                "init_xB_raw": "xB_init.raw",
                "init_Ctot_raw": "Ctot_init.raw",
                "init_meta": "init_meta.json",
                "params": portable_path(param_path),
                "nsteps": 2,
                "dt_code": float(values["dt"]),
            })

    manifest = {
        "schema": "coarse4_stage1_smoke_manifest_v1",
        "status": "PRECALIBRATION_HARD_GATE_ONLY",
        "coarse_model_name": MODEL_NAME,
        "coarse_model_version": MODEL_VERSION,
        "physical_interface_width_claimed": False,
        "grid": [args.grid, args.grid, args.grid],
        "dx_nm": COARSE_DX_NM,
        "lambda_nm": COARSE_LAMBDA_NM,
        "lambda_over_dx": COARSE_LAMBDA_NM / COARSE_DX_NM,
        "gamma_J_m2": inputs.gamma,
        "W": float(pf["W"]),
        "kappa": float(pf["kappa_phi"]),
        "D_alpha_code": float(pf["D_alpha"]),
        "L_phi_diff_code": finite_lphi_diff,
        "fine_reference_hash": fine_hash,
        "fine_reference_assets": [str(p.relative_to(ROOT)) for p in reference_assets],
        "coarse_calibration_hash": calibration_hash,
        "calibration_protocol": CALIBRATION_PROTOCOL,
        "coarse_uncertainty_version": UNCERTAINTY_VERSION,
        "mechanics_precision_mode": MECHANICS_PRECISION_MODE,
        "mechanics_acceptance_mode": MECHANICS_ACCEPTANCE_MODE,
        "mechanics_eta_floor_version": MECHANICS_ETA_FLOOR_VERSION,
        "mechanics_eta_floor": MECHANICS_ETA_FLOOR,
        "mechanics_eta_accept": MECHANICS_ETA_ACCEPT,
        "mechanics_safety_factor": MECHANICS_SAFETY_FACTOR,
        "mechanics_double_oracle_contract_hash": MECHANICS_DOUBLE_ORACLE_CONTRACT_HASH,
        "mechanics_residual_normalization_version": MECHANICS_RESIDUAL_NORMALIZATION_VERSION,
        "initial_state": state_meta,
        "cases": cases,
        "GP_source_reintegrated": False,
        "S3_reintegrated": False,
    }
    (out / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    print(out)
    print(f"fine_reference_hash={fine_hash}")
    print(f"coarse_calibration_hash={calibration_hash}")
    print(f"D_alpha_code={float(pf['D_alpha']):.17e}")
    print(f"L_phi_diff_code={finite_lphi_diff:.17e}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
