#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.analysis.analyze_cnt_peak_table import parse_summary_file


def _parse_float(value: str | None) -> float | None:
    if value in (None, "", "nan", "NaN"):
        return None
    try:
        f = float(value)
    except ValueError:
        return None
    if f == f:
        return f
    return None


def _radius_from_voxels(voxel_count: int, dx_nm: float) -> float:
    volume_nm3 = voxel_count * (dx_nm ** 3)
    return ((3.0 * volume_nm3) / (4.0 * math.pi)) ** (1.0 / 3.0)


def _continue_dir_name(mode: str) -> str:
    mode = (mode or "").strip().lower()
    if mode == "minimize-continue":
        return "continue_min_1"
    return "continue_dyn_1"


def _resolve_repo_style_path(raw: str | None, results_root: Path) -> Path | None:
    if not raw:
        return None
    p = Path(raw)
    if p.is_absolute():
        return p
    parts = p.parts
    if parts and parts[0] == "Results":
        return results_root / Path(*parts[1:])
    return results_root.parent / p


def _summary_candidates(row: dict[str, str], results_root: Path) -> list[Path]:
    radius = _parse_float(row.get("START_RADIUS_NM"))
    if radius is None:
        raise ValueError("row lacks START_RADIUS_NM")
    temp_c = float(row["TEMP_C"])
    nx = int(row["NX"])
    ny = int(row["NY"])
    nz = int(row["NZ"])
    dt = float(row["DT"])
    steps = int(row.get("NSTEPS", "0") or 0)
    xb = float(row["XB_OUT"])
    base = row["BASE_CASE_TAG"]
    outer = f"chel_T{int(round(temp_c))}_cuda_{nx}x{ny}x{nz}_dt{dt:g}_steps{steps}_r{radius:.3f}nm_xB{xb:.3f}"
    case_dir = f"{base}_r{radius:.6f}".replace(".", "p")
    continue_dir = _continue_dir_name(row.get("MODE", ""))
    run_root = results_root / outer
    source_summary = _resolve_repo_style_path(row.get("CONTINUE_SOURCE_SUMMARY_PATH"), results_root)
    if source_summary is None:
        source_summary = _resolve_repo_style_path(row.get("SUMMARY_PATH"), results_root)
    if source_summary is not None:
        try:
            run_root = source_summary.parent.parent
        except IndexError:
            pass
    return [
        run_root / continue_dir / "summary.txt",
        run_root / continue_dir / f"summary_{continue_dir}.txt",
        run_root / case_dir / f"summary_{case_dir}.txt",
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description="Summarize dynamics-continue growth from manifest rows and result summaries.")
    parser.add_argument("--manifest", type=Path, required=True, help="continue manifest csv generated by submit_dynamics_continue_batch.py")
    parser.add_argument("--results-root", type=Path, default=Path("Results"), help="results root used to locate continue summaries")
    parser.add_argument("--dx-nm", type=float, default=0.1, help="grid spacing used to convert voxel count to equivalent radius")
    parser.add_argument("--output", type=Path, default=None, help="optional csv output")
    args = parser.parse_args()

    manifest = args.manifest.expanduser().resolve()
    results_root = args.results_root.expanduser().resolve()

    rows = list(csv.DictReader(manifest.open(newline="", encoding="utf-8")))
    records: list[dict[str, object]] = []
    for row in rows:
        start_radius = _parse_float(row.get("START_RADIUS_NM"))
        if start_radius is None:
            continue
        candidates = _summary_candidates(row, results_root)
        summary_path = next((p for p in candidates if p.exists()), candidates[0])
        summary_data = {}
        if summary_path.exists():
            summary_data = parse_summary_file(summary_path)
        voxel_count = summary_data.get("voxel_count")
        grown_radius = None
        if isinstance(voxel_count, int):
            grown_radius = _radius_from_voxels(voxel_count, args.dx_nm)
        record = {
            "base_case_tag": row.get("BASE_CASE_TAG", ""),
            "queue_name": row.get("QUEUE_NAME", ""),
            "strain": row.get("STRAIN", ""),
            "start_radius_nm": start_radius,
            "summary_path": str(summary_path),
            "summary_exists": int(summary_path.exists()),
            "voxel_count": voxel_count if isinstance(voxel_count, int) else None,
            "grown_equiv_radius_nm": grown_radius,
            "delta_growth_nm": (grown_radius - start_radius) if grown_radius is not None else None,
            "status": row.get("STATUS", ""),
        }
        for key, value in summary_data.items():
            if key == "summary_path":
                continue
            record[key] = value
        records.append(record)

    out_path = args.output.expanduser().resolve() if args.output else manifest.parent / "dynamics_continue_growth_summary.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(records[0].keys()) if records else [])
        if records:
            writer.writeheader()
            writer.writerows(records)

    print(out_path)
    print(f"records={len(records)}")
    print(f"with_summary={sum(1 for r in records if r['summary_exists'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
