#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.analysis.analyze_cnt_peak_table import fit_local_peak, parse_summary_file


def _resolve_repo_path(repo_root: Path, rel_or_abs: str) -> Path:
    p = Path(rel_or_abs)
    if p.is_absolute():
        return p
    return repo_root / p


def main() -> int:
    parser = argparse.ArgumentParser(description="Summarize CNT scan results from a single guide CSV.")
    parser.add_argument("--guide-csv", type=Path, required=True, help="guide_cnt_scan.csv generated by setup_cnt_workflow.py")
    parser.add_argument("--repo-root", "--results-root", dest="repo_root", type=Path, default=Path("."), help="repo root containing Results/")
    parser.add_argument("--output", type=Path, default=None, help="output summary csv")
    args = parser.parse_args()

    guide_csv = args.guide_csv.expanduser().resolve()
    repo_root = args.repo_root.expanduser().resolve()
    workflow_dir = guide_csv.parent.parent
    output = args.output.expanduser().resolve() if args.output else (workflow_dir / "cnt_scan" / "current_results_master_table_fitted.csv")
    output.parent.mkdir(parents=True, exist_ok=True)

    with guide_csv.open(newline="", encoding="utf-8") as f:
        guide_rows = list(csv.DictReader(f))

    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    meta_by_base: dict[str, dict[str, str]] = {}
    for row in guide_rows:
        base = row["base_case_tag"]
        grouped[base].append(row)
        meta_by_base[base] = row

    records: list[dict[str, object]] = []
    for base_case_tag, rows in sorted(grouped.items(), key=lambda kv: (kv[1][0]["mode"], float(kv[1][0]["strain"]))):
        rows_sorted = sorted(rows, key=lambda r: float(r["radius_nm"]))
        points: list[tuple[float, float]] = []
        point_info: dict[float, dict[str, object]] = {}
        for row in rows_sorted:
            radius_nm = float(row["radius_nm"])
            energy_csv = _resolve_repo_path(repo_root, row["energy_csv_rel"])
            summary_path = _resolve_repo_path(repo_root, row["summary_rel"])
            if not energy_csv.exists():
                continue
            with energy_csv.open(newline="", encoding="utf-8") as f:
                energy_rows = list(csv.DictReader(f))
            if not energy_rows or "F_total_CNT_hat" not in energy_rows[-1]:
                continue
            fcnt = float(energy_rows[-1]["F_total_CNT_hat"])
            points.append((radius_nm, fcnt))
            point_info[radius_nm] = {
                "summary_path": summary_path,
                "case_dir_path": _resolve_repo_path(repo_root, row["case_dir_rel"]),
                "energy_csv_path": energy_csv,
            }

        peak_found = False
        peak_index = None
        rc_cnt = None
        fcnt_peak = None
        rc_fit = None
        fcnt_fit = None
        fit_method = ""
        delta_discrete = None
        delta_fit = None

        if points:
            vals = [p[1] for p in points]
            peak_index = max(range(len(vals)), key=lambda i: vals[i])
            rc_cnt = points[peak_index][0]
            fcnt_peak = points[peak_index][1]
            if 0 < peak_index < len(points) - 1:
                peak_found = True
                rc_fit, fcnt_fit, fit_method = fit_local_peak(points, peak_index)
                delta_discrete = rc_cnt - float(meta_by_base[base_case_tag]["rc_schur_nm"])
                if rc_fit is not None:
                    delta_fit = rc_fit - float(meta_by_base[base_case_tag]["rc_schur_nm"])

        summary_data: dict[str, object] = {}
        if rc_cnt is not None:
            summary_file = point_info.get(rc_cnt, {}).get("summary_path")
            if isinstance(summary_file, Path) and summary_file.exists():
                summary_data = parse_summary_file(summary_file)
            else:
                summary_data = {"summary_path": str(summary_file) if summary_file else ""}

        expected_points = len(rows_sorted)
        available_points = len(points)
        if available_points == 0:
            status = "not_started"
        elif available_points < expected_points:
            status = "partial_peak_found" if peak_found else "partial_no_peak_yet"
        else:
            status = "complete_peak_found" if peak_found else "complete_no_peak_in_window"

        meta = meta_by_base[base_case_tag]
        record = {
            "workflow_name": meta["workflow_name"],
            "guide_csv": str(guide_csv),
            "base_case_tag": base_case_tag,
            "mode": meta["mode"],
            "strain": float(meta["strain"]),
            "T_C": float(meta["T_C"]),
            "xB_out": float(meta["xB_out"]),
            "rc_schur_nm": float(meta["rc_schur_nm"]),
            "window_nm": float(meta["window_nm"]),
            "step_nm": float(meta["step_nm"]),
            "expected_points": expected_points,
            "available_points": available_points,
            "peak_found": int(peak_found),
            "rc_cnt_nm": rc_cnt,
            "delta_cnt_minus_schur_nm": delta_discrete,
            "F_CNT_peak_hat": fcnt_peak,
            "rc_cnt_fit_nm": rc_fit,
            "delta_fit_minus_schur_nm": delta_fit,
            "F_CNT_fit_hat": fcnt_fit,
            "fit_method": fit_method,
            "peak_index": peak_index,
            "status": status,
        }
        record.update(summary_data)
        records.append(record)

    with output.open("w", newline="", encoding="utf-8") as f:
        if records:
            writer = csv.DictWriter(f, fieldnames=list(records[0].keys()))
            writer.writeheader()
            writer.writerows(records)
        else:
            f.write("")

    print(output)
    print(f"records={len(records)}")
    print(f"complete_peak_found={sum(1 for r in records if r['status'] == 'complete_peak_found')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
